<!--
Codes Generated By VForm:
https://www.vform666.com
-->

<template>
  <el-form :model="formData" ref="vForm" :rules="rules" label-position="left" label-width="72px" size="medium"
    @submit.native.prevent>
    <el-row>
      <el-col :span="24" class="grid-cell">
        <el-form-item label="姓名" prop="userName" class="required label-center-align">
          <el-input v-model="formData.name" type="text" placeholder="输入姓名" clearable></el-input>
        </el-form-item>
      </el-col>
      <el-col :span="24" class="grid-cell">
        <el-form-item label="性别" prop="sex" class="required label-center-align">
          <el-radio-group v-model="formData.sex">
            <el-radio v-for="(item, index) in sexOptions" :key="index" :label="item.value"
              :disabled="item.disabled" style="{display: inline}">{{item.label}}</el-radio>
          </el-radio-group>
        </el-form-item>
      </el-col>
      <el-col :span="24" class="grid-cell">
        <el-form-item label="出生日期" prop="birthday" class="required label-center-align">
          <el-date-picker v-model="formData.birthday" type="date" class="full-width-input" format="yyyy-MM-dd"
            value-format="yyyy-MM-dd" clearable></el-date-picker>
        </el-form-item>
      </el-col>
      <el-col :span="24" class="grid-cell">
        <el-form-item label="证件号码" prop="idCard" class="required label-center-align">
          <el-input v-model="formData.idCard" type="text" placeholder="请输入身份证" clearable></el-input>
        </el-form-item>
      </el-col>
      <el-col :span="24" class="grid-cell">
        <el-form-item label="民族" prop="nation" class="required label-center-align">
          <el-select v-model="formData.nation" class="full-width-input" clearable>
            <el-option v-for="(item, index) in nationOptions" :key="index" :label="item.value"
              :value="item.value" :disabled="item.disabled"></el-option>
          </el-select>
        </el-form-item>
      </el-col>
      <el-col :span="24" class="grid-cell">
        <el-form-item label="联系方式" prop="phone" class="required label-center-align">
          <el-input v-model="formData.phone" type="text" placeholder="请输入手机号" clearable></el-input>
        </el-form-item>
      </el-col>
      <el-col :span="24" class="grid-cell">
        <el-form-item label="居中类型" prop="live_type" class="required label-center-align">
          <el-radio-group v-model="formData.live_type">
            <el-radio v-for="(item, index) in live_typeOptions" :key="index" :label="item.value"
              :disabled="item.disabled" style="{display: inline}">{{item.label}}</el-radio>
          </el-radio-group>
        </el-form-item>
      </el-col>
      <el-col :span="24" class="grid-cell">
        <el-form-item label="所属机构" prop="org_name" class="required label-center-align">
          <el-select v-model="formData.org_name" class="full-width-input" clearable>
            <el-option v-for="(item, index) in org_nameOptions" :key="index" :label="item.value"
              :value="item.value" :disabled="item.disabled"></el-option>
          </el-select>
        </el-form-item>
      </el-col>
      <el-col :span="24" class="grid-cell">
        <el-form-item label="建档时间" prop="creatTime" class="label-center-align">
          <el-date-picker v-model="formData.creatTime" type="date" class="full-width-input" :disabled="true"
            format="yyyy-MM-dd" value-format="yyyy-MM-dd" clearable></el-date-picker>
        </el-form-item>
      </el-col>
      <el-col :span="24" class="grid-cell">
        <el-form-item label="详细地址" prop="address" class="required">
          <el-input v-model="formData.address" type="text" placeholder="请输入居住详细地址" clearable></el-input>
        </el-form-item>
      </el-col>
      <el-col :span="24" class="grid-cell">
        <el-form-item label="建档状态" prop="status" class="required">
          <el-select v-model="formData.status" class="full-width-input" clearable>
            <el-option v-for="(item, index) in statusOptions" :key="index" :label="item.value"
              :value="item.value" :disabled="item.disabled"></el-option>
          </el-select>
        </el-form-item>
      </el-col>
    </el-row>
  </el-form>

</template>

<script>
export default {
  components: {},
  props: {},
  data () {
    return {
      formData: {
        userName: '',
        sex: '',
        birthday: null,
        idCard: '',
        nation: '',
        phone: '',
        live_type: '',
        org_name: '',
        creatTime: null,
        address: '',
        status: ''
      },
      rules: {
        userName: [{
          required: true,
          message: '字段值不可为空'
        }, {
          pattern: /^[一-龥]+$/,
          trigger: ['blur', 'change'],
          message: '姓名格式错误'
        }],
        sex: [{
          required: true,
          message: '字段值不可为空'
        }, {
          pattern: /^\d+(\.\d+)?$/,
          trigger: ['blur', 'change'],
          message: '性别格式错误'
        }],
        birthday: [{
          required: true,
          message: '字段值不可为空'
        }, {
          pattern: /^[一-龥]+$/,
          trigger: ['blur', 'change'],
          message: '出生日期格式错误'
        }],
        idCard: [{
          required: true,
          message: '字段值不可为空'
        }],
        nation: [{
          required: true,
          message: '字段值不可为空'
        }, {
          pattern: /^[一-龥]+$/,
          trigger: ['blur', 'change'],
          message: ''
        }],
        phone: [{
          required: true,
          message: '字段值不可为空'
        }, {
          pattern: /^[1][3-9][0-9]{9}$/,
          trigger: ['blur', 'change'],
          message: '手机号格式不正确'
        }],
        live_type: [{
          required: true,
          message: '字段值不可为空'
        }],
        org_name: [{
          required: true,
          message: '字段值不可为空'
        }],
        address: [{
          required: true,
          message: '字段值不可为空'
        }],
        status: [{
          required: true,
          message: '字段值不可为空'
        }]
      },
      sexOptions: [{
        'label': '男',
        'value': 1
      }, {
        'label': '女',
        'value': 2
      }],
      nationOptions: [{
        'label': 'select 2',
        'value': 2
      }, {
        'label': 'select 3',
        'value': 3
      }],
      live_typeOptions: [{
        'label': '户籍',
        'value': '1'
      }, {
        'label': '非户籍',
        'value': 2
      }],
      org_nameOptions: [{
        'label': 'select 1',
        'value': 1
      }, {
        'label': 'select 2',
        'value': 2
      }, {
        'label': 'select 3',
        'value': 3
      }],
      statusOptions: [{
        'label': 'select 1',
        'value': 1
      }, {
        'label': 'select 2',
        'value': 2
      }, {
        'label': 'select 3',
        'value': 3
      }]
    }
  },
  computed: {},
  watch: {},
  created () {},
  mounted () {},
  methods: {
    submitForm () {
      this.$refs['vForm'].validate(valid => {
        if (!valid) return
        // TODO: 提交表单
      })
    },
    resetForm () {
      this.$refs['vForm'].resetFields()
    }
  }
}

</script>

<style lang="scss">
  .el-input-number.full-width-input,
  .el-cascader.full-width-input {
    width: 100% !important;
  }

  .el-form-item--medium {
    .el-radio {
      line-height: 36px !important;
    }

    .el-rate {
      margin-top: 8px;
    }
  }

  .el-form-item--small {
    .el-radio {
      line-height: 32px !important;
    }

    .el-rate {
      margin-top: 6px;
    }
  }

  .el-form-item--mini {
    .el-radio {
      line-height: 28px !important;
    }

    .el-rate {
      margin-top: 4px;
    }
  }

  .clear-fix:before,
  .clear-fix:after {
    display: table;
    content: "";
  }

  .clear-fix:after {
    clear: both;
  }

  .float-right {
    float: right;
  }

</style>

<style lang="scss" scoped>
  div.table-container {
    table.table-layout {
      width: 100%;
      table-layout: fixed;
      border-collapse: collapse;

      td.table-cell {
        display: table-cell;
        height: 36px;
        border: 1px solid #e1e2e3;
      }
    }
  }

  div.tab-container {}

  .label-left-align ::v-deep .el-form-item__label {
    text-align: left;
  }

  .label-center-align ::v-deep .el-form-item__label {
    text-align: center;
  }

  .label-right-align ::v-deep .el-form-item__label {
    text-align: right;
  }

  .custom-label {}

  .static-content-item {
    min-height: 20px;
    display: flex;
    align-items: center;

    ::v-deep .el-divider--horizontal {
      margin: 0;
    }
  }

</style>
